---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-countermeasure-vilaverde-rocks-v1alpha1-countermeasure
  failurePolicy: Fail
  name: mcountermeasure.kb.io
  rules:
  - apiGroups:
    - countermeasure.vilaverde.rocks
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - countermeasures
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-eventsource-vilaverde-rocks-v1alpha1-prometheus
  failurePolicy: Fail
  name: mprometheus.kb.io
  rules:
  - apiGroups:
    - eventsource.vilaverde.rocks
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - prometheuses
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-countermeasure-vilaverde-rocks-v1alpha1-countermeasure
  failurePolicy: Fail
  name: vcountermeasure.kb.io
  rules:
  - apiGroups:
    - countermeasure.vilaverde.rocks
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - countermeasures
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-eventsource-vilaverde-rocks-v1alpha1-prometheus
  failurePolicy: Fail
  name: vprometheus.kb.io
  rules:
  - apiGroups:
    - eventsource.vilaverde.rocks
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - prometheuses
  sideEffects: None
