# permissions for end users to edit countermeasures.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: countermeasure-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: k8s-countermeasures
    app.kubernetes.io/part-of: k8s-countermeasures
    app.kubernetes.io/managed-by: kustomize
  name: countermeasure-editor-role
rules:
- apiGroups:
  - countermeasure.vilaverde.rocks
  resources:
  - countermeasures
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - countermeasure.vilaverde.rocks
  resources:
  - countermeasures/status
  verbs:
  - get
