---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
- apiGroups:
  - operator.vilaverde.rocks
  resources:
  - countermeasures
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.vilaverde.rocks
  resources:
  - countermeasures/finalizers
  verbs:
  - update
- apiGroups:
  - operator.vilaverde.rocks
  resources:
  - countermeasures/status
  verbs:
  - get
  - patch
  - update
