apiVersion: operator.vilaverde.rocks/v1alpha1
kind: CounterMeasure
metadata:
  name: clean-tmp
spec:
  prometheus:
    service:
      name: prometheus-operated
      namespace: monitoring
    interval: 15s
    alert:
      name: CPUThrottlingHigh
      includePending: true
  actions:
  - name: foo
    command: ["rm", "-Rf", "/tmp"]