apiVersion: operator.vilaverde.rocks/v1alpha1
kind: CounterMeasure
metadata:
  name: clean-tmp
spec:
  prometheus:
    service:
      name: prometheus-operated
      namespace: monitoring
    alert:
      name: HTTP_404
      includePending: false
  actions:
  - name: foo
    delete: 
      name: ${labels.pod}
      namespace: ${labels.namespace}
      kind: Pod
