apiVersion: operator.vilaverde.rocks/v1alpha1
kind: CounterMeasure
metadata:
  name: clean-tmp
spec:
  prometheus:
    service:
      name: prometheus-operated
      namespace: monitoring
    alert:
      name: HTTP_404
      includePending: false
  actions:
  - name: delete-pod
    delete:
      targetObjectRef: 
        name: "{{ .Labels.pod }}"
        namespace: "{{ .Labels.namespace }}"
        kind: Pod
        apiVersion: v1
