apiVersion: operator.vilaverde.rocks/v1alpha1
kind: CounterMeasure
metadata:
  name: clean-tmp
spec:
  prometheus:
    expr: ALERTS{alertname="CPUThrottlingHigh", alertstate="pending", severity="info", pod="node-exporter-nrhwl"} == 1
    interval: 15s
    service:
      name: prometheus-operated
      namespace: monitoring
  actions:
  - name: foo
    command: ["rm", "-Rf", "/tmp"]