apiVersion: operator.vilaverde.rocks/v1alpha1
kind: CounterMeasure
metadata:
  name: basic-auth-p8s
  labels:
    app.kubernetes.io/name: countermeasure
    app.kubernetes.io/instance: countermeasure-sample
    app.kubernetes.io/part-of: k8s-countermeasures
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: k8s-countermeasures
spec:
  prometheus:
    service:
      name: prometheus-operated
      namespace: monitoring
    auth:
      secretRef:
        name: p8s-basic-auth
    alert:
      name: HTTP_404
      includePending: false
  actions:
  - name: delete-pod
    delete:
      targetObjectRef: 
        name: "{{ .Labels.pod }}"
        namespace: "{{ .Labels.namespace }}"
        kind: Pod
        apiVersion: v1
