apiVersion: countermeasure.vilaverde.rocks/v1alpha1
kind: CounterMeasure
metadata:
  name: debug-action
  labels:
    app.kubernetes.io/name: countermeasure
    app.kubernetes.io/instance: countermeasure-sample
    app.kubernetes.io/part-of: k8s-countermeasures
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: k8s-countermeasures
spec:
  onEvent:
    named: HTTP_404
    fromSource:
      name: prometheus
      namespace: ns-custom
  actions:
  - name: debug-pod
    debug:
      name: debugger
      command:
      - "touch"
      args:
      - "/proc/1/root/iwashere.txt"
      image: busybox:1.28
      stdin: true
      podRef: 
        name: "{{ .Data.pod }}"
        namespace: "{{ .Data.namespace }}"
        container: main
