apiVersion: countermeasure.vilaverde.rocks/v1alpha1
kind: CounterMeasure
metadata:
  name: delete-action
  labels:
    app.kubernetes.io/name: countermeasure
    app.kubernetes.io/instance: countermeasure-sample
    app.kubernetes.io/part-of: k8s-countermeasures
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: k8s-countermeasures
spec:
  onEvent:
    name: HTTP_404
    sourceSelector:
      matchLabels:
        app.kubernetes.io/name: p8s-source
        app.kubernetes.io/instance: dev
  actions:
  - name: delete-pod
    delete:
      targetObjectRef: 
        name: "{{ .Data.pod }}"
        namespace: "{{ .Data.namespace }}"
        kind: Pod
        apiVersion: v1
