apiVersion: eventsource.vilaverde.rocks/v1alpha1
kind: Prometheus
metadata:
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/instance: prometheus-sample
    app.kubernetes.io/part-of: k8s-countermeasures
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: k8s-countermeasures
  name: prometheus-sample
spec:
  # TODO(user): Add fields here
