apiVersion: countermeasure.vilaverde.rocks/v1alpha1
kind: CounterMeasure
metadata:
  name: json-patch-action
  labels:
    app.kubernetes.io/name: countermeasure
    app.kubernetes.io/instance: countermeasure-sample
    app.kubernetes.io/part-of: k8s-countermeasures
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: k8s-countermeasures
spec:
  prometheus:
    service:
      name: prometheus-operated
      namespace: monitoring
    alert:
      name: HTTP_404
      includePending: false
  actions:
  - name: custom-restart-pod
    patch:
      patchType: application/json-patch+json
      yamlTemplate: |
        - op: add
          path: /spec/template/spec/containers/0/env/-
          value: { "name": "ENV.3", "value": "value3" }
      targetObjectRef: 
        apiVersion: apps/v1
        kind: Deployment
        name: monitored-app
        namespace: ns-custom
        
        
