apiVersion: countermeasure.vilaverde.rocks/v1alpha1
kind: CounterMeasure
metadata:
  name: json-patch-action
  labels:
    app.kubernetes.io/name: countermeasure
    app.kubernetes.io/instance: countermeasure-sample
    app.kubernetes.io/part-of: k8s-countermeasures
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: k8s-countermeasures
spec:
  onEvent:
    name: HTTP_404
    sourceSelector:
      matchLabels:
        app.kubernetes.io/name: p8s-source
        app.kubernetes.io/instance: dev
  actions:
  - name: custom-restart-pod
    patch:
      patchType: application/json-patch+json
      yamlTemplate: |
        - op: add
          path: /spec/template/spec/containers/0/env/-
          value: { "name": "ENV.3", "value": "value3" }
      targetObjectRef: 
        apiVersion: apps/v1
        kind: Deployment
        name: monitored-app
        namespace: ns-custom
        
        
