apiVersion: operator.vilaverde.rocks/v1alpha1
kind: CounterMeasure
metadata:
  labels:
    app.kubernetes.io/name: countermeasure
    app.kubernetes.io/instance: countermeasure-sample
    app.kubernetes.io/part-of: k8s-countermeasures
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: k8s-countermeasures
  name: countermeasure-sample
spec:
  # TODO(user): Add fields here
