apiVersion: countermeasure.vilaverde.rocks/v1alpha1
kind: CounterMeasure
metadata:
  name: patch-strategic-action
  labels:
    app.kubernetes.io/name: countermeasure
    app.kubernetes.io/instance: countermeasure-sample
    app.kubernetes.io/part-of: k8s-countermeasures
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: k8s-countermeasures
spec:
  prometheus:
    service:
      name: prometheus-operated
      namespace: monitoring
    alert:
      name: HTTP_404
      includePending: false
      suppressionPolicy:
        duration: 1m
  actions:
  - name: change-env
    patch:
      patchType: application/strategic-merge-patch+json
      yamlTemplate: |
        spec:
          template:
            spec: 
              containers:
              - name: main
                env:
                - name: ENV.0
                  value: '{{ range (index .Object.spec.template.spec.containers 0).env }}{{- if eq .name "ENV.1" }}{{ .value }}{{- end -}}{{ end }}'
                - name: ENV.1
                  value: '{{ range (index .Object.spec.template.spec.containers 0).env }}{{- if eq .name "ENV.0" }}{{ .value }}{{- end -}}{{ end }}'
      targetObjectRef: 
        apiVersion: apps/v1
        kind: Deployment
        name: monitored-app
        namespace: ns-custom
        
        
