apiVersion: eventsource.vilaverde.rocks/v1alpha1
kind: Prometheus
metadata:
  name: p8s-source
  labels:
    app.kubernetes.io/name: p8s-source
    app.kubernetes.io/instance: dev
spec:
  serviceRef:
    name: prometheus-operated
    namespace: monitoring
  auth:
    secretRef:
      name: p8s-basic-auth
  includePending: false
  pollingInterval: 30s