apiVersion: countermeasure.vilaverde.rocks/v1alpha1
kind: CounterMeasure
metadata:
  name: restart-action
  labels:
    app.kubernetes.io/name: countermeasure
    app.kubernetes.io/instance: countermeasure-sample
    app.kubernetes.io/part-of: k8s-countermeasures
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: k8s-countermeasures
spec:
  onEvent:
    name: HTTP_404
    suppressionPolicy:
      duration: 120s
    sourceSelector:
      matchLabels:
        app.kubernetes.io/name: p8s-source
        app.kubernetes.io/instance: dev
  actions:
  - name: delete-pod
    restart:
      deploymentRef: 
        name: monitored-app
        namespace: ns-custom
