apiVersion: operator.vilaverde.rocks/v1alpha1
kind: CounterMeasure
metadata:
  name: debug-action
spec:
  prometheus:
    service:
      name: prometheus-operated
      namespace: monitoring
    alert:
      name: HTTP_404
      includePending: false
  actions:
  - name: debug-pod
    debug:
      name: debugger
      command:
      - "touch"
      args:
      - "/proc/1/root/iwashere.txt"
      image: busybox:1.28
      stdin: true
      podRef: 
        name: "{{ .Labels.pod }}"
        namespace: "{{ .Labels.namespace }}"
        container: main
