name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version-file: 'go.mod'
        check-latest: true
        cache: true

    - name: Run tests
      run: make test

    - name: Run build
      run: make build
